CREATE DATABASE COLABORAMUNDO;

USE COLABORAMUNDO;

CREATE TABLE USUARIO_COMUM (
	USU_ID INT IDENTITY (1,1),
	USU_NOME VARCHAR (50) NOT NULL ,
	USU_EMAIL VARCHAR (70) NOT NULL ,
	USU_SENHA VARCHAR (11) NOT NULL,
	USU_PAIS VARCHAR (40) NOT NULL,
	CONSTRAINT PK_USU_ID PRIMARY KEY (USU_ID)
);

CREATE TABLE PROJETO_USUARIO (
	USU_ID INT,
	PRO_ID INT,
	CONSTRAINT PK_PROJETO_USUARIO PRIMARY KEY (USU_ID, PRO_ID),
	CONSTRAINT FK_USUARIO FOREIGN KEY (USU_ID) REFERENCES  USUARIO_COMUM(USU_ID),
	CONSTRAINT FK_PROJETO FOREIGN KEY (PRO_ID) REFERENCES PROJETO (PRO_ID)
);

CREATE TABLE COLABORACAO (
	COL_ID INT IDENTITY (1,1),
	USU_ID INT,
	COL_DESC VARCHAR (200) NOT NULL ,
	COL_DATA DATE NOT NULL,
	CONSTRAINT PK_COL_ID PRIMARY KEY (COL_ID),
	CONSTRAINT FK_COLABORACAO_USU_ID FOREIGN KEY (USU_ID) REFERENCES USUARIO_COMUM(USU_ID)
);

CREATE TABLE ESPECIALISTA (
ESP_ID INT IDENTITY (1,1),
ESP_NOME VARCHAR (50) NOT NULL,
ESP_EMAIL VARCHAR (70) NOT NULL,
ESP_SENHA VARCHAR (11) NOT NULL,
ESP_PAIS VARCHAR (40) NOT NULL,
);

CREATE TABLE EXPERTISE (
EXP_ID INT IDENTITY (1,1),
ESP_ID INT,
EXP_NOME VARCHAR (50) NOT NULL,
EXP_AREA VARCHAR (70) NOT NULL,
EXP_DESC VARCHAR (300) NOT NULL,
EXP_NIVEL CHAR (1) NOT NULL,
EXP_CERTIFICACOES VARCHAR (100) NOT NULL,
CONSTRAINT UK_EXP_AREA UNIQUE (EXP_AREA),
CONSTRAINT PK_EXP_ID PRIMARY KEY (EXP_ID), 
CONSTRAINT FK_EXPERTISE_ESPECIALISTA_ID FOREIGN KEY (ESP_ID) REFERENCES ESPECIALISTA (ESP_ID)
);

ALTER TABLE ESPECIALISTA 
ADD CONSTRAINT PK_ESP_ID PRIMARY KEY (ESP_ID);


CREATE TABLE MENTORIA (
MEN_ID INT IDENTITY (1,1),
COL_ID INT,
MEN_DESC VARCHAR (300) NOT NULL,
MEN_QUANT_SESSOES INT NOT NULL,
MEN_FOCO VARCHAR (150) NOT NULL,
CONSTRAINT PK_MEN_ID PRIMARY KEY (MEN_ID),
CONSTRAINT FK_MENTORIA_COLABORACAO_ID FOREIGN KEY (COL_ID) REFERENCES COLABORACAO(COL_ID)
);

ALTER TABLE MENTORIA
ADD  ESP_ID INT;


ALTER TABLE MENTORIA
ADD  CONSTRAINT FK_MENTORIA_ESPECIALISTA_ID FOREIGN KEY (ESP_ID) REFERENCES ESPECIALISTA (ESP_ID);

CREATE TABLE VOLUNTARIADO (
VOL_ID INT IDENTITY (1,1),
COL_ID INT,
VOL_QUANT INT NOT NULL,
VOL_DESC VARCHAR (200) NOT NULL,
VOL_ATIVIDADE VARCHAR (300) NOT NULL,
VOL_HORAS INT NOT NULL,
CONSTRAINT PK_VOL_ID PRIMARY KEY (VOL_ID),
CONSTRAINT FK_VOLUNTARIADO_COLABORACAO_ID FOREIGN KEY (COL_ID) REFERENCES COLABORACAO(COL_ID)
);

CREATE TABLE FINANCEIRO (
FIN_ID INT IDENTITY (1,1),
COL_ID INT,
FIN_DESC VARCHAR (200) NOT NULL,
FIN_VALOR FLOAT NOT NULL,
FIN_PERIODICIDADE VARCHAR (100) NOT NULL,
FIN_DESTINO VARCHAR (100) NOT NULL,
CONSTRAINT PK_FIN_ID PRIMARY KEY (FIN_ID),
CONSTRAINT FK_FINANCEIRO_COLABORACAO_ID FOREIGN KEY (COL_ID) REFERENCES COLABORACAO(COL_ID)
);

CREATE TABLE PROJETO (
	PRO_ID INT PRIMARY KEY IDENTITY (1,1),
	PRO_NOME VARCHAR(50) NOT NULL,
	PRO_DESC VARCHAR(200) NOT NULL,
	PRO_DATA_INICIO DATE NOT NULL,
	PRO_STATUS VARCHAR(30) NOT NULL,
	PRO_PRAZO DATE NOT NULL,
);

CREATE TABLE ODS_PROJETO (
ODS_ID INT,
PRO_ID INT,
CONSTRAINT PK_ODS_PROJETO PRIMARY KEY (ODS_ID, PRO_ID),
CONSTRAINT FK_ODS FOREIGN KEY (ODS_ID) REFERENCES ODS(ODS_ID),
CONSTRAINT FK_PROJETO_ODS FOREIGN KEY (PRO_ID) REFERENCES PROJETO(PRO_ID),
);

CREATE TABLE ODS (
ODS_ID INT IDENTITY (1,1),
ODS_NOME VARCHAR (100) NOT NULL,
ODS_DESC VARCHAR (200) NOT NULL,
CONSTRAINT PK_ODS_ID PRIMARY KEY (ODS_ID)
);

CREATE TABLE TAREFA (
    TAR_ID INT PRIMARY KEY IDENTITY (1,1),
    PRO_ID INT FOREIGN KEY REFERENCES PROJETO(PRO_ID),
    TAR_NOME VARCHAR(200) NOT NULL,
    TAR_DESC VARCHAR(200) NOT NULL,
    TAR_DATA_INICIO DATE NOT NULL,
    TAR_DATA_FIM DATE NOT NULL,
);

CREATE TABLE DOCUMENTO (
    DOC_ID INT PRIMARY KEY IDENTITY (1,1),
    PRO_ID INT FOREIGN KEY REFERENCES PROJETO(PRO_ID),
    DOC_NOME VARCHAR(200) NOT NULL,
    DOC_TIPO VARCHAR(100) NOT NULL,
    DOC_DESC VARCHAR(300) NOT NULL,
    DOC_DATA DATE	NOT NULL,
);


