CREATE DATABASE COLABORAMUNDO;

USE COLABORAMUNDO;

CREATE TABLE USUARIO_COMUM (
	USU_ID INT IDENTITY (1,1),
	USU_NOME VARCHAR (50) NOT NULL ,
	USU_EMAIL VARCHAR (70) NOT NULL ,
	USU_SENHA VARCHAR (11) NOT NULL,
	USU_PAIS VARCHAR (40) NOT NULL,
	CONSTRAINT PK_USU_ID PRIMARY KEY (USU_ID)
);

CREATE TABLE PROJETO_USUARIO (
	USU_ID INT,
	PRO_ID INT,
	CONSTRAINT PK_PROJETO_USUARIO PRIMARY KEY (USU_ID, PRO_ID),
	CONSTRAINT FK_USUARIO FOREIGN KEY (USU_ID) REFERENCES  USUARIO_COMUM(USU_ID),
	CONSTRAINT FK_PROJETO FOREIGN KEY (PRO_ID) REFERENCES PROJETO (PRO_ID)
);

CREATE TABLE COLABORACAO (
	COL_ID INT IDENTITY (1,1),
	USU_ID INT,
	COL_DESC VARCHAR (200) NOT NULL ,
	COL_DATA DATE NOT NULL,
	CONSTRAINT PK_COL_ID PRIMARY KEY (COL_ID),
	CONSTRAINT FK_COLABORACAO_USU_ID FOREIGN KEY (USU_ID) REFERENCES USUARIO_COMUM(USU_ID)
);

CREATE TABLE PROJETO (
	PRO_ID INT PRIMARY KEY IDENTITY (1,1),
	PRO_NOME VARCHAR(50) NOT NULL,
	PRO_DESC VARCHAR(200) NOT NULL,
	PRO_DATA_INICIO DATE NOT NULL,
	PRO_STATUS VARCHAR(30) NOT NULL,
	PRO_PRAZO DATE NOT NULL,
);

CREATE TABLE TAREFA (
    TAR_ID INT PRIMARY KEY IDENTITY (1,1),
    PRO_ID INT FOREIGN KEY REFERENCES PROJETO(PRO_ID),
    TAR_NOME VARCHAR(200) NOT NULL,
    TAR_DESC VARCHAR(200) NOT NULL,
    TAR_DATA_INICIO DATE NOT NULL,
    TAR_DATA_FIM DATE NOT NULL,
);

CREATE TABLE DOCUMENTO (
    DOC_ID INT PRIMARY KEY IDENTITY (1,1),
    PRO_ID INT FOREIGN KEY REFERENCES PROJETO(PRO_ID),
    DOC_NOME VARCHAR(200) NOT NULL,
    DOC_TIPO VARCHAR(100) NOT NULL,
    DOC_DESC VARCHAR(300) NOT NULL,
    DOC_DATA DATE	NOT NULL,
);

